### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by tn2009** [Cleric-K/FlySky-i6X_Firmware_BugFix#1]
New version firmware for Flysky I6X 1.0.51.1440 - 20 SEP 2019. Please check this official firmware on the presence of a bug.
https://www.flysky-cn.com/fsi6x - New firmware in Download section.

**Comment by Cleric-K** [comment]
Thanks. I'll check asap.

**Comment by Cleric-K** [comment]
The firmware still has the bug. Flysky must be joking...

Anyway. I have patched it and uploaded the new updater.

Thanks for letting me know about the update.
