### ISSUE TITLE
does not open because of "is not a valid Win32 application" error

### ISSUE THREAD

**Issue by Jazzbari** [Cleric-K/FlySky-i6X_Firmware_BugFix#10]
Tried downloading several times. I am running Windows 7 home edition.

**Comment by Jazzbari** [comment]
The download file also shows 0 bytes

**Comment by Cleric-K** [comment]
Try with another browser or disable antivirus software. Some people have reported that antivirus is software misdetects the exe as a virus.

**Comment by Jazzbari** [comment]
Worked after changing from Firefox to Chrome but had to change the File extension from ".download to .exe" I changed the file name from "Undefined 214724.download" to FS-i6X_23_Oct-2019_bugfix.exe just to keep track in my computer.Thanks so much for taking the time to give your support.Al

Alfred Mezquida



 

    On Monday, December 28, 2020, 5:45:58 AM EST, Cleric-K <notifications@github.com> wrote:  
 
 


Try with another browser or disable antivirus software. Some people have reported that antivirus is software misdetects the exe as a virus.
