### ISSUE TITLE
does flysky i6have same bug？

### ISSUE THREAD

**Issue by 1074748905** [Cleric-K/FlySky-i6X_Firmware_BugFix#6]
does flysky i6have same bug？

**Comment by Cleric-K** [comment]
No. Only i6X.

**Comment by neoxic** [comment]
What about i6S?

**Comment by Cleric-K** [comment]
I'm not sure about i6s but I think it doesn't have problem. It can be easily verified by saving short blackbox log (can be on the desk with props removed) with debug mode set to `RC_INTERPOLATION` or `RC_SMOOTHING`, then make some smooth movements with the sticks, and then check in bbox explorer if the _raw_ rc data also moves smoothly.

**Comment by neoxic** [comment]
Thanks for bringing it up, @Cleric-K ! Much appreciated. I'll do my own research on the FS-i6S when I have a chance.
