### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by Igoracy** [Cleric-K/FlySky-i6X_Firmware_BugFix#7]
hello
after updating the radio in firmware ver. shows me 1.0 Apr 05 2018
Is that how it should be?
I've also noticed that I now have 12 chanells in "display" 
and it stopped working on the simulator.

**Comment by Cleric-K** [comment]
Did you install this version:
https://github.com/Cleric-K/FlySky-i6X_Firmware_BugFix/releases/tag/v1.2

**Comment by Igoracy** [comment]
Yes I installed this one. My radio came with an update from 2019.

**Comment by Igoracy** [comment]
weird. Even the original 2017 update doesn't work, but when I downloaded it from Mirko fpv, it did and I could upload the original 2019 update. Soon I will see if when I update with the bugfix version it will be the same as at the beginning.

**Comment by Igoracy** [comment]
...so it's the same again
after the update, the radio shows that I have the 2018 version. It doesn't matter from which verse it is updated.

**Comment by Cleric-K** [comment]
I don't see how this is possible...
There's simply no text string that has `2018` in the whole firmware - I have no idea where it can come from. I wonder if you have some newer version of the transmitter that has somewhat different hardware. When did you buy it?

The fact that you can't install the original 2017 version is also strange. How does it fail? What message you get?

**Comment by Igoracy** [comment]
I bought it in May of this year, so maybe it's really something about that. After the update, I just have a message that it's been successful. After upgrading to any version anyway it shows 1.0.42.1

**Comment by Igoracy** [comment]
In this case, how can I see if the bugfix works after updating?

**Comment by Igoracy** [comment]
um, I know it sounds weird, but I packed this exe file to zip and now it works. The file that MirkoFPV provided was already packed and it worked right so I packed it too and it works. Maybe this has something to do with windows detecting this file as a virus. (although I disabled the defender)
