### ISSUE TITLE
Can you make Trainer Mode accept 8 channel from the Student?

### ISSUE THREAD

**Issue by human890209** [Cleric-K/FlySky-i6X_Firmware_BugFix#8]
Hi,
i6X's Trainer Mode only lets the student operate CH1~CH4, only 4 channels. Could you modify the firmware to accept all the 8 channel values from the Student PPM signal when Trainer Mode is activated?
I'm planning to make a driving cockpit for my FPV RC car, which has a drive wheel, pads, handbrake, gearbox handle... I tested some sensors and an Arduino to send out the PPM as a Student controller for I6X which worked.  But 4 Channel is hard to add more interesting things like camera rotation, turning lights, NOS button...
If I6X has 8 channels of student control, it will be a great RC controller with Trainer Mode.

**Comment by Cleric-K** [comment]
Hi,

I don't think I'll be able to help. When I was working on the bugfix I was able to reverse engineer only the part where it sends the channels and that's where the fix is. The remaining part of the firmware is quite large and I have no idea where to look for the trainer code. Sorry.

**Comment by human890209** [comment]
Thank you for your replay!
