### ISSUE TITLE
GFX Editor

### ISSUE THREAD

**Issue by Multisoft1978** [Cleric-K/FlySky-i6X_Firmware_BugFix#9]
```
For fix firmware
1B9F3 128 48 Font
1C17A 56 36 FS AFHDS
1C292 52 14 Helicopter
1C2FA 52 14 Planer
1C362 64 12 SYSTEM
1C3E2 30 12 settings
1C459 23 7 battery
1C471 8 8 ->
1C479 76 12 FACTORY
1C511 93 12 FUNCTIONS
1C5CB 46 12 MENU
1C627 30 32 FlySky i6x
1C6A0 8 8 \/
1C6A7 82 15 AFHDS2A
1C74B 28 10 battery
1C782 16 32 switch down
1C7C2 16 32 switch up
1C803 32 32 sticks

for Original firmware
1F9F3 128 48 Font
2017A 56 36 FS AFHDS
20292 52 14 Helicopter
202FA 52 14 Planer

e.t.c

```

**Comment by Cleric-K** [comment]
Can you explain?

**Comment by Multisoft1978** [comment]
> Can you explain?

Use GFXEditor program to change font and pictures.
Code:
https://github.com/qba667/FlySkyI6/tree/master/GFXeditor
EXE file https://www.rcgroups.com/forums/showpost.php?p=39513924&postcount=183

**Comment by Cleric-K** [comment]
Ok.
The offsets are different because the FlySky firmware itself is newer version. The bug fix does not change the offsets of data.

Seems the gfx editor has to be adapted for the different versions that ship from FlySky. Or it has to be made more intelligent and detect the offsets by itself.

**Comment by Tikev62360** [comment]
Salut pour ma part impossible de modifier les icônes sur i6x
